# -*- coding: utf-8 -*-
"""Data collection from book to scrape with paging

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NiZZyPejSXrFgf1HHgGTJ8goErTjRzQf
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

base_url = "http://books.toscrape.com/catalogue/page-{}.html"
all_books = []

# Loop through all 50 pages
for page in range(1, 51):
    print(f"Scraping page {page}...")
    url = base_url.format(page)
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    books = soup.find_all('article', class_='product_pod')

    for book in books:
        title = book.h3.a['title']
        price = book.find('p', class_='price_color').text.strip()
        availability = book.find('p', class_='instock availability').text.strip()
        rating_class = book.find('p')['class'][1]

        all_books.append({
            'Title': title,
            'Price': price,
            'Availability': availability,
            'Rating': rating_class
        })

# Create DataFrame
df = pd.DataFrame(all_books)

# Save to CSV
df.to_csv("books_data.csv", index=False)
print("✅ All data saved to 'books_data.csv'")